name: Publish on npm and tag with "beta"

on:
  # Shows the manual trigger in GitHub UI
  # helpful as a back-up in case the GitHub Actions Workflow fails
  workflow_dispatch:

  push:
    branches:
      - gitpod

jobs:
  # NOTE: this job requires curl, jq and yarn
  # All of them are included in ubuntu-latest.
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish npm package and tag "beta"
        run: yarn publish:npm
        env:
          ENVIRONMENT: "staging"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TAG: "beta"
          # Since this only runs on a merge into gitpod, we can't use github.event.number
          # so we instead use the word "beta" and the PR merge commit SHA
          PR_NUMBER_AND_COMMIT_SHA: beta-${{ github.sha }}
